package su.afk.yummy.tv.domain.videodownload.model

data class VideoDownloadItem(
    val id: Long,
    val animeId: Int,
    val animeTitle: String,
    val posterUrl: String,
    val episode: String,
    val videoId: Int,
    val playerName: String,
    val playerId: Int?,
    val dubbing: String,
    val iframeUrl: String,
    val screenshotUrl: String,
    val qualityLabel: String,
    val streamUrl: String,
    val headers: Map<String, String>,
    val cacheKey: String,
    val status: VideoDownloadStatus,
    val progress: Float,
    val bytesDownloaded: Long,
    val totalBytes: Long?,
    val errorMessage: String?,
    val exportStatus: VideoExportStatus,
    val exportProgress: Float,
    val exportDirectoryUri: String?,
    val exportedFileUri: String?,
    val exportErrorMessage: String?,
    val createdAt: Long,
    val updatedAt: Long,
)
