package su.afk.yummy.tv.core.model.settings

data class SettingsSnapshot(
    val appTheme: AppTheme,
    val backgroundStyle: BackgroundStyle,
    val posterQuality: PosterQuality,
    val posterCardSize: PosterCardSize,
    val showTopTitleYear: Boolean,
    val newEpisodesSectionEnabled: Boolean,
    val newEpisodesSources: Set<NewEpisodesSource>,
    val newEpisodesHideWatched: Boolean,
    val showLibraryTitleYear: Boolean,
    val libraryContinueWatchingCardSize: LibraryContinueWatchingCardSize,
    val preferredPlayer: PreferredPlayer,
    val preferredVideoQuality: PreferredVideoQuality,
    val watchNextEnabled: Boolean,
    val previewCacheSize: Int,
    val autoSkipOpeningsEndings: Boolean,
    val autoSkipDelaySeconds: Int,
    val showOpeningOnTimeline: Boolean,
    val autoPlayNextEpisode: Boolean,
    val screenOffAfterEnd: Boolean,
    val nextEpisodeSwitchDelaySeconds: Int,
    val playerControlsAutoHideSeconds: Int,
    val askDubbingOnWatch: Boolean,
    val pictureInPictureEnabled: Boolean,
    val playerOrientationMode: PlayerOrientationMode,
    val suggestNextEpisodeOnWatched: Boolean,
    val watchedThresholds: WatchedThresholds,
    val refreshContinueWatchingProgressOnLaunch: Boolean,
    val tvPlayerVolumeKeysEnabled: Boolean,
    val advancedPlayerVolumeEnabled: Boolean,
    val volumeStabilizationEnabled: Boolean,
    val playerBufferProfile: PlayerBufferProfile,
    val browserUserAgentProfile: BrowserUserAgentProfile = BrowserUserAgentProfile.DEFAULT,
    val videoExportAutoEnabled: Boolean,
    val yaniApplicationToken: String,
    val contentLanguage: YaniContentLanguage,
    val detailsButtonOrder: List<DetailsButtonAction>,
    val libraryTabOrder: List<LibraryTabKind> = LibraryTabKind.entries,
)
