package su.afk.yummy.tv.feature.player.navigator

import androidx.navigation3.runtime.NavKey
import su.afk.yummy.tv.feature.player.IPlayerNavigator
import su.afk.yummy.tv.feature.player.PlayerSkips
import javax.inject.Inject

class PlayerNavigator @Inject constructor() : IPlayerNavigator {
    override fun getPlayerDest(
        iframeUrl: String,
        animeTitle: String,
        episode: String,
        playerName: String,
        dubbing: String,
        episodeUrls: List<String>,
        episodeNumbers: List<String>,
        episodeVideoIds: List<Int>,
        currentEpisodeIndex: Int,
        screenshotUrls: List<String>,
        animeId: Int,
        posterUrl: String,
        allDubbingNames: List<String>,
        currentDubbingIndex: Int,
        allDubbingEpisodeUrls: List<List<String>>,
        allDubbingEpisodeNumbers: List<List<String>>,
        allDubbingEpisodeVideoIds: List<List<Int>>,
        allDubbingViews: List<Int>,
        allBalancerNames: List<String>,
        currentBalancerIndex: Int,
        allBalancerDubbingNames: List<List<String>>,
        allBalancerEpisodeUrls: List<List<List<String>>>,
        allBalancerEpisodeNumbers: List<List<List<String>>>,
        allBalancerEpisodeVideoIds: List<List<List<Int>>>,
        allBalancerDubbingViews: List<List<Int>>,
        episodeSkips: List<PlayerSkips>,
        allDubbingEpisodeSkips: List<List<PlayerSkips>>,
        allBalancerEpisodeSkips: List<List<List<PlayerSkips>>>,
    ): NavKey = PlayerDestination(
        iframeUrl = iframeUrl,
        animeTitle = animeTitle,
        episode = episode,
        playerName = playerName,
        dubbing = dubbing,
        episodeUrls = episodeUrls,
        episodeNumbers = episodeNumbers,
        episodeVideoIds = episodeVideoIds,
        currentEpisodeIndex = currentEpisodeIndex,
        screenshotUrls = screenshotUrls,
        animeId = animeId,
        posterUrl = posterUrl,
        allDubbingNames = allDubbingNames,
        currentDubbingIndex = currentDubbingIndex,
        allDubbingEpisodeUrls = allDubbingEpisodeUrls,
        allDubbingEpisodeNumbers = allDubbingEpisodeNumbers,
        allDubbingEpisodeVideoIds = allDubbingEpisodeVideoIds,
        allDubbingViews = allDubbingViews,
        allBalancerNames = allBalancerNames,
        currentBalancerIndex = currentBalancerIndex,
        allBalancerDubbingNames = allBalancerDubbingNames,
        allBalancerEpisodeUrls = allBalancerEpisodeUrls,
        allBalancerEpisodeNumbers = allBalancerEpisodeNumbers,
        allBalancerEpisodeVideoIds = allBalancerEpisodeVideoIds,
        allBalancerDubbingViews = allBalancerDubbingViews,
        episodeSkips = episodeSkips,
        allDubbingEpisodeSkips = allDubbingEpisodeSkips,
        allBalancerEpisodeSkips = allBalancerEpisodeSkips,
    )
}
