package su.afk.yummy.tv.feature.account.account.model

enum class AccountUiError {
    CAPTCHA_RESPONSE_EMPTY,
    CAPTCHA_EXPIRED,
    CAPTCHA_LOAD_FAILED,
    CAPTCHA_REJECTED,
    CREDENTIALS_REQUIRED,
    LOGOUT_FAILED,
    REFRESH_FAILED,
    OPEN_NOTIFICATION_FAILED,
    SIGN_IN_FAILED,
    LOAD_PROFILE_STATISTICS_FAILED,
    LOAD_NOTIFICATIONS_FAILED,
    UPDATE_NOTIFICATION_FAILED,
    UPDATE_NOTIFICATIONS_FAILED,
}
